services:
    _defaults:
        public: true

    redeye_graphql.type_resolver: '@Redeye\GraphQLBundle\Resolver\TypeResolver'
    redeye_graphql.query_resolver: '@Redeye\GraphQLBundle\Resolver\QueryResolver'
    redeye_graphql.mutation_resolver: '@Redeye\GraphQLBundle\Resolver\MutationResolver'
    redeye_graphql.access_resolver: '@Redeye\GraphQLBundle\Resolver\AccessResolver'
    redeye_graphql.cache_compiler: '@Redeye\GraphQLBundle\Generator\TypeGenerator'
    redeye_graphql.react.promise_adapter: '@Redeye\GraphQLBundle\Executor\Promise\Adapter\ReactPromiseAdapter'
    redeye_graphql.request_executor: '@Redeye\GraphQLBundle\Request\Executor'
    redeye_graphql.request_parser: '@Redeye\GraphQLBundle\Request\Parser'
    redeye_graphql.request_batch_parser: '@Redeye\GraphQLBundle\Request\BatchParser'
    redeye_graphql.arguments_transformer: '@Redeye\GraphQLBundle\Transformer\ArgumentsTransformer'

    redeye_graphql.type_factory:
        alias: 'Redeye\GraphQLBundle\Definition\Builder\TypeFactory'
        public: false
